"""Map retained transcript words onto rendered timeline time."""

import re
from dataclasses import dataclass

from minicut.semantic_segment import SemanticSegment
from minicut.timeline import Timeline
from minicut.transcript import Word


@dataclass(frozen=True, slots=True)
class MappedWord:
    """One retained transcript token translated to output time."""

    word_id: str
    text: str
    start_ms: int
    end_ms: int
    clip_id: str

    def __post_init__(self) -> None:
        if not self.word_id.strip() or not self.clip_id.strip():
            raise ValueError("mapped Word and Clip IDs must not be blank")
        if self.start_ms < 0 or self.end_ms <= self.start_ms:
            raise ValueError("mapped Word time range must be non-empty")


@dataclass(frozen=True, slots=True)
class SubtitleCue:
    """One non-empty subtitle interval ready for serialization."""

    start_ms: int
    end_ms: int
    text: str

    def __post_init__(self) -> None:
        if self.start_ms < 0 or self.end_ms <= self.start_ms:
            raise ValueError("subtitle cue time range must be non-empty")
        if not self.text.strip():
            raise ValueError("subtitle cue text must not be blank")


_TIMESTAMP = re.compile(
    r"^(?P<hours>\d{2,}):(?P<minutes>[0-5]\d):(?P<seconds>[0-5]\d),"
    r"(?P<milliseconds>\d{3})$"
)


def _format_timestamp(milliseconds: int) -> str:
    hours, remainder = divmod(milliseconds, 3_600_000)
    minutes, remainder = divmod(remainder, 60_000)
    seconds, millis = divmod(remainder, 1_000)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{millis:03d}"


def _parse_timestamp(value: str) -> int:
    match = _TIMESTAMP.fullmatch(value)
    if match is None:
        raise ValueError("invalid SRT timestamp")
    return (
        int(match["hours"]) * 3_600_000
        + int(match["minutes"]) * 60_000
        + int(match["seconds"]) * 1_000
        + int(match["milliseconds"])
    )


def _validate_cue_sequence(
    cues: tuple[SubtitleCue, ...], video_duration_ms: int
) -> None:
    if video_duration_ms < 0:
        raise ValueError("video duration must not be negative")
    previous_end_ms = 0
    for cue in cues:
        if cue.start_ms < previous_end_ms:
            raise ValueError("subtitle cues must be monotonic and non-overlapping")
        if cue.end_ms > video_duration_ms:
            raise ValueError("subtitle cue exceeds video duration")
        previous_end_ms = cue.end_ms


def build_word_cues(
    mapped_words: tuple[MappedWord, ...], video_duration_ms: int
) -> tuple[SubtitleCue, ...]:
    """Create one strictly timed cue for each retained word."""
    cues = tuple(
        SubtitleCue(word.start_ms, word.end_ms, word.text)
        for word in mapped_words
        if word.text.strip()
    )
    _validate_cue_sequence(cues, video_duration_ms)
    return cues


def render_srt(cues: tuple[SubtitleCue, ...], video_duration_ms: int) -> str:
    """Serialize validated cues as standards-compatible SubRip text."""
    _validate_cue_sequence(cues, video_duration_ms)
    blocks = (
        f"{index}\n{_format_timestamp(cue.start_ms)} --> "
        f"{_format_timestamp(cue.end_ms)}\n{cue.text}"
        for index, cue in enumerate(cues, start=1)
    )
    rendered = "\n\n".join(blocks)
    return f"{rendered}\n" if rendered else ""


def parse_srt(content: str) -> tuple[SubtitleCue, ...]:
    """Strictly parse SubRip generated by MiniCut for round-trip verification."""
    normalized = content.replace("\r\n", "\n").strip()
    if not normalized:
        return ()
    cues: list[SubtitleCue] = []
    for expected_index, block in enumerate(normalized.split("\n\n"), start=1):
        lines = block.splitlines()
        if len(lines) < 3 or lines[0] != str(expected_index):
            raise ValueError("invalid SRT cue index or content")
        start, separator, end = lines[1].partition(" --> ")
        if separator != " --> ":
            raise ValueError("invalid SRT cue timing")
        cues.append(
            SubtitleCue(
                _parse_timestamp(start),
                _parse_timestamp(end),
                "\n".join(lines[2:]),
            )
        )
    return tuple(cues)


def map_retained_words(
    timeline: Timeline,
    segments: tuple[SemanticSegment, ...],
    words: tuple[Word, ...],
) -> tuple[MappedWord, ...]:
    """Translate only retained Segment words from source to output time."""
    segments_by_id = {segment.segment_id: segment for segment in segments}
    words_by_id = {word.word_id: word for word in words}
    if len(segments_by_id) != len(segments):
        raise ValueError("Segment IDs must be unique for subtitle mapping")
    if len(words_by_id) != len(words):
        raise ValueError("Word IDs must be unique for subtitle mapping")

    mapped: list[MappedWord] = []
    mapped_word_ids: set[str] = set()
    for clip in timeline.clips:
        clip_word_ids: list[str] = []
        for segment_id in clip.segment_ids:
            segment = segments_by_id.get(segment_id)
            if segment is None:
                raise ValueError("Timeline Clip references an unknown Segment")
            clip_word_ids.extend(segment.word_ids)

        clip_words: list[Word] = []
        for word_id in dict.fromkeys(clip_word_ids):
            word = words_by_id.get(word_id)
            if word is None:
                raise ValueError("retained Segment references an unknown Word")
            if word_id in mapped_word_ids:
                raise ValueError("retained Word is mapped by more than one Clip")
            if (
                word.start_ms < clip.source_range.start_ms
                or word.end_ms > clip.source_range.end_ms
            ):
                raise ValueError("retained Word lies outside its Clip source range")
            clip_words.append(word)

        for word in sorted(
            clip_words,
            key=lambda item: (item.start_ms, item.end_ms, item.word_id),
        ):
            offset_ms = clip.output_range.start_ms - clip.source_range.start_ms
            mapped.append(
                MappedWord(
                    word.word_id,
                    word.text,
                    word.start_ms + offset_ms,
                    word.end_ms + offset_ms,
                    clip.clip_id,
                )
            )
            mapped_word_ids.add(word.word_id)
    return tuple(mapped)


__all__ = [
    "MappedWord",
    "SubtitleCue",
    "build_word_cues",
    "map_retained_words",
    "parse_srt",
    "render_srt",
]
