import {useEffect,useRef,useState} from "react";
import {applyBatchCoverTemplate,coversSaved,type BatchCoverResult,type CoverApplyMode} from "./coverApi";
import {useCoverTemplateLibrary} from "./useCoverTemplateLibrary";

export function BatchCoverTemplates({project,collection,outputs,selected,disabled,onBusy}:{project:string;collection:string;outputs:{output_id:string;title:string;revision:number}[];selected:string[];disabled:boolean;onBusy:(busy:boolean)=>void}){
  const library=useCoverTemplateLibrary();const [selection,setSelection]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [results,setResults]=useState<BatchCoverResult[]>([]);const lock=useRef(false);
  const current=library.templates.find(item=>item.template_id===selection);
  const blocked=disabled||busy||library.loading||!!library.loadError||!current||selected.length===0;
  useEffect(()=>{onBusy(busy);return()=>onBusy(false);},[busy,onBusy]);
  async function apply(mode:CoverApplyMode){if(blocked||!current||lock.current)return;lock.current=true;setBusy(true);setError("");setResults([]);const chosen=outputs.filter(item=>selected.includes(item.output_id));try{const rows=await applyBatchCoverTemplate(project,collection,chosen.map(({output_id,revision})=>({output_id,revision})),current.template_id,mode);setResults(rows);window.dispatchEvent(new CustomEvent(coversSaved,{detail:{project,collection,outputs:rows.filter(row=>row.version!==null).map(row=>row.output_id)}}));}catch(reason){setError(reason instanceof Error?reason.message:"批量应用封面失败");}finally{lock.current=false;setBusy(false);}}
  return <details open className="batch-cover-templates"><summary>批量应用封面模板</summary><label>批量封面模板<select aria-label="批量封面模板" disabled={disabled||busy} value={selection} onChange={event=>{setSelection(event.target.value);setError("");setResults([]);}}><option value="">请选择封面模板</option>{library.templates.map(item=><option key={item.template_id} value={item.template_id}>{item.name}</option>)}{selection&&!current&&<option value={selection}>模板已删除或未找到</option>}</select></label><p className="helper-text">对已选的 {selected.length} 条作品应用并保存封面。保留各自标题文字和选帧；不会导出或重新渲染视频。请先保存或放弃当前封面草稿。</p><div className="preset-apply-actions"><button type="button" disabled={blocked} onClick={()=>void apply("title")}>仅标题样式 · 保存到已选作品</button><button type="button" disabled={blocked} onClick={()=>void apply("all")}>全部设计 · 保存到已选作品</button></div>{library.loading&&<p role="status">正在读取封面模板…</p>}{library.loadError&&<p role="alert">{library.loadError}<button type="button" onClick={library.refresh}>重试读取封面模板库</button></p>}{!library.loading&&!library.loadError&&!library.templates.length&&<p className="helper-text">先在单作品「管理我的封面模板」中另存一个模板。</p>}{busy&&<p role="status">正在应用并保存封面…</p>}{error&&<p role="alert">{error}</p>}{results.length>0&&<><p role="status">已保存 {results.filter(row=>row.version!==null).length} 条；失败 {results.filter(row=>row.error).length} 条。</p><ul>{results.map(row=><li key={row.output_id}>{outputs.find(item=>item.output_id===row.output_id)?.title??row.output_id}：{row.error?<span role="alert">{row.error}</span>:`封面已保存 · v${row.version}`}</li>)}</ul></>}</details>;
}
