import {CoverTemplateControls} from "./CoverTemplateControls";
import {useEffect,useRef,useState,type PointerEvent} from "react";
import {coversSaved,coverRoute,loadCover,saveCover,previewCover,uploadCoverBackground,type CoverDesign,type CoverBox,type CoverRecord} from "./coverApi";
import type {HighlightClip} from "./api";
import {registerDraftGuard} from "./draftNavigation";

const sizes={"9:16":[1080,1920],"16:9":[1920,1080],"1:1":[1080,1080],"3:4":[1080,1440]} as const;
function layout(ratio:CoverDesign["aspect_ratio"]){return ratio==="16:9"?{frame:{x:.08,y:.06,width:.84,height:.64},title_box:{x:.08,y:.74,width:.84,height:.22},font_size:76}:{frame:{x:.08,y:.14,width:.84,height:.46},title_box:{x:.08,y:.66,width:.84,height:.25},font_size:88};}
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));
export function CoverEditor({project,collection,output,revision,clips,onDirty,onSaved}:{project:string;collection:string;output:string;revision:number;clips:HighlightClip[];onDirty:(value:boolean)=>void;onSaved:(version:number|undefined)=>void}){
  const route=coverRoute(project,collection,output);const storageKey=`minicut-cover-draft:${project}:${collection}:${output}`;
  const [saved,setSaved]=useState<CoverRecord>();const [design,setDesign]=useState<CoverDesign>();
  const [fonts,setFonts]=useState<{id:string;name:string}[]>([]);const [error,setError]=useState("");const [previewError,setPreviewError]=useState("");
  const [image,setImage]=useState("");const [warnings,setWarnings]=useState<string[]>([]);const [working,setBusy]=useState(false);const [templateBusy,setTemplateBusy]=useState(false);const busy=working||templateBusy;const [rendering,setRendering]=useState(false);const [retry,setRetry]=useState(0);
  const [target,setTarget]=useState<"frame"|"title_box">("frame");const [format,setFormat]=useState<"png"|"jpg">("png");
  const canvas=useRef<HTMLDivElement>(null);const lock=useRef(false);const imageUrl=useRef("");
  const drag=useRef<{x:number;y:number;box:CoverBox;resize:boolean;target:"frame"|"title_box";width:number;height:number}|undefined>(undefined);
  const dirty=!!design&&!!saved&&JSON.stringify(design)!==JSON.stringify(saved.design);
  const retained=clips.filter(c=>!c.deleted);
  useEffect(()=>()=>onDirty(false),[onDirty]);
  useEffect(()=>{onDirty(dirty||busy);},[saved,dirty,busy,onDirty]);
  useEffect(()=>{const refresh=(event:Event)=>{const detail=(event as CustomEvent<{project:string;collection:string;outputs:string[]}>).detail;if(detail?.project===project&&detail.collection===collection&&detail.outputs.includes(output))setRetry(value=>value+1);};window.addEventListener(coversSaved,refresh);return()=>window.removeEventListener(coversSaved,refresh);},[project,collection,output]);
  useEffect(()=>{const controller=new AbortController();setSaved(undefined);setDesign(undefined);onSaved(undefined);setError("");loadCover(route,revision,controller.signal).then(record=>{
    if(controller.signal.aborted)return;setSaved(record);setFonts(record.fonts??[]);onSaved(record.version);
    let draft:CoverDesign|undefined;try{const value=JSON.parse(sessionStorage.getItem(storageKey)??"null");if(value?.base_version===record.version)draft=value.design;}catch{/* Browser storage may be disabled. */}
    setDesign(draft??record.design);
  }).catch(reason=>{if(!controller.signal.aborted)setError(String(reason.message??reason));});return()=>controller.abort();},[route,revision,retry,storageKey,onSaved]);
  useEffect(()=>{if(!design||!saved)return;try{if(dirty)sessionStorage.setItem(storageKey,JSON.stringify({base_version:saved.version,design}));else sessionStorage.removeItem(storageKey);}catch{/* Keep the in-memory draft. */}},[design,saved,dirty,storageKey]);
  useEffect(()=>{if(!dirty)return;const unload=(event:BeforeUnloadEvent)=>event.preventDefault();window.addEventListener("beforeunload",unload);const unregister=registerDraftGuard(proceed=>{if(window.confirm("封面尚未保存，放弃修改并离开？")){try{sessionStorage.removeItem(storageKey);}catch{}proceed();}});return()=>{window.removeEventListener("beforeunload",unload);unregister();};},[dirty,storageKey]);
  useEffect(()=>{const controller=new AbortController();if(!design||design.mode!=="design"){setRendering(false);setPreviewError("");return;}setRendering(true);const timer=setTimeout(()=>{previewCover(route,revision,design,controller.signal).then(value=>{if(controller.signal.aborted)return;const url=URL.createObjectURL(value.blob);if(imageUrl.current)URL.revokeObjectURL(imageUrl.current);imageUrl.current=url;setImage(url);setWarnings(value.warnings);setPreviewError("");setRendering(false);}).catch(reason=>{if(!controller.signal.aborted){setPreviewError(String(reason.message??reason));setRendering(false);}});},250);return()=>{controller.abort();clearTimeout(timer);};},[route,revision,design]);
  useEffect(()=>()=>{if(imageUrl.current)URL.revokeObjectURL(imageUrl.current);},[]);
  function change(patch:Partial<CoverDesign>){setDesign(previous=>previous?{...previous,...patch}:previous);setError("");}
  async function save(){if(!design||!saved||lock.current)return;lock.current=true;setBusy(true);setError("");try{const record=await saveCover(route,revision,saved.version,design);setSaved(record);setDesign(record.design);onSaved(record.version);}catch(reason){setError(reason instanceof Error?reason.message:"保存封面失败");}finally{lock.current=false;setBusy(false);}}
  async function upload(file:File){if(lock.current)return;lock.current=true;setBusy(true);setError("");try{if(file.size>15*1024*1024)throw new Error("背景图片不能超过 15 MB");const identity=await uploadCoverBackground(route,revision,file);change({background_image:identity});}catch(reason){setError(reason instanceof Error?reason.message:"上传失败");}finally{lock.current=false;setBusy(false);}}
  function pointerDown(event:PointerEvent<HTMLElement>,resize:boolean,element:"frame"|"title_box"){
    if(!design||busy||!canvas.current)return;event.preventDefault();event.stopPropagation();setTarget(element);const rect=canvas.current.getBoundingClientRect();drag.current={x:event.clientX,y:event.clientY,box:{...design[element]},resize,target:element,width:rect.width,height:rect.height};event.currentTarget.setPointerCapture(event.pointerId);
  }
  function pointerMove(event:PointerEvent<HTMLElement>){const value=drag.current;if(!value)return;const dx=(event.clientX-value.x)/value.width,dy=(event.clientY-value.y)/value.height;const box=value.resize?{...value.box,width:clamp(value.box.width+dx,.05,2),height:clamp(value.box.height+dy,.05,2)}:{...value.box,x:clamp(value.box.x+dx,-1,1),y:clamp(value.box.y+dy,-1,1)};change({[value.target]:box});}
  function endDrag(){drag.current=undefined;}
  if(!design||!saved)return <section aria-label="封面设计"><h2>封面设计</h2>{error?<><p role="alert">{error}</p><button onClick={()=>setRetry(v=>v+1)}>重新载入封面</button></>:<p role="status">正在读取封面设置…</p>}</section>;
  const [width,height]=sizes[design.aspect_ratio];const box=design[target];const frameMs=design.frame_ms??retained[0]?.start_ms??0;
  const selectedClip=retained.find(c=>c.start_ms<=frameMs&&frameMs<c.end_ms);
  return <section className="cover-editor" aria-label="封面设计"><h2>封面设计</h2><p className="helper-text">封面独立保存，不重新渲染视频。</p>
    <CoverTemplateControls project={project} collection={collection} output={output} revision={revision} design={design} onChange={setDesign} disabled={working} onBusy={setTemplateBusy}/>
    <fieldset disabled={busy}><label>封面模式<select value={design.mode} onChange={e=>change({mode:e.target.value as CoverDesign["mode"]})}><option value="first_frame">直接使用成片第一帧</option><option value="design">自定义封面</option></select></label>
    {design.mode==="design"&&<>
      <label>封面尺寸<select value={design.aspect_ratio} onChange={e=>{const ratio=e.target.value as CoverDesign["aspect_ratio"];change({aspect_ratio:ratio,...layout(ratio)});}}><option value="9:16">竖屏 9:16 · 1080 × 1920</option><option value="16:9">横屏 16:9 · 1920 × 1080</option><option value="1:1">方形 1:1 · 1080 × 1080</option><option value="3:4">竖版 3:4 · 1080 × 1440</option></select></label>
      <p className="helper-text">切换尺寸会重置排版，不改变视频画幅。</p>
      <div className="cover-canvas" ref={canvas} style={{aspectRatio:`${width}/${height}`}} aria-label="封面画布">
        {image?<img src={image} alt="自定义封面预览" draggable={false}/>:<p>正在生成封面预览…</p>}
        {(["frame","title_box"] as const).map(element=>{const value=design[element];return <div key={element} role="button" tabIndex={0} aria-label={element==="frame"?"视频帧位置":"标题位置"} className={`cover-element ${target===element?"selected":""}`} style={{left:`${value.x*100}%`,top:`${value.y*100}%`,width:`${value.width*100}%`,height:`${value.height*100}%`}} onPointerDown={event=>pointerDown(event,false,element)} onPointerMove={pointerMove} onPointerUp={endDrag} onPointerCancel={endDrag} onLostPointerCapture={endDrag} onKeyDown={event=>{if(busy)return;if(!["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(event.key))return;event.preventDefault();setTarget(element);const step=event.shiftKey?.02:.005;change({[element]:{...value,x:clamp(value.x+(event.key==="ArrowRight"?step:event.key==="ArrowLeft"?-step:0),-1,1),y:clamp(value.y+(event.key==="ArrowDown"?step:event.key==="ArrowUp"?-step:0),-1,1)}});}}>
          <span className="cover-element-label">{element==="frame"?"视频帧":"标题"}</span><button type="button" className="cover-resize" aria-label={element==="frame"?"缩放视频帧":"缩放标题框"} onPointerDown={event=>pointerDown(event,true,element)} onPointerMove={pointerMove} onPointerUp={endDrag} onPointerCancel={endDrag} onLostPointerCapture={endDrag}/>
        </div>;})}
      </div>
      <p role="status" className="helper-text">{rendering?"正在更新预览…":"拖动画面或标题移动位置；拖动右下角调整大小。方向键微调，Shift 加速。"}</p>
      {previewError&&<p role="alert">{previewError}</p>}{warnings.map(warning=><p className="cover-warning" key={warning}>{warning}</p>)}
      <details><summary>背景</summary><label>背景颜色<input type="color" value={design.background_color} onChange={e=>change({background_color:e.target.value})}/></label><label>上传背景图片<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value="";}}/></label><p className="helper-text">JPG、PNG、WebP，最大 15 MB；图片保存在本地项目中。</p>
        {design.background_image&&<><button onClick={()=>change({background_image:null})}>改用纯色背景</button>{(["background_scale","background_x","background_y"] as const).map(key=><label key={key}>{{background_scale:"背景缩放",background_x:"背景水平位置",background_y:"背景垂直位置"}[key]}<input type="range" min={key==="background_scale"?1:0} max={key==="background_scale"?4:1} step={.01} value={design[key]} onChange={e=>change({[key]:Number(e.target.value)})}/></label>)}</>}
      </details>
      <details><summary>视频帧</summary><label>选择保留片段<select value={selectedClip?.instance_id??""} onChange={e=>{const clip=retained.find(c=>c.instance_id===e.target.value);if(clip)change({frame_ms:clip.start_ms});}}><option value="" disabled>请重新选择片段</option>{retained.map((clip,index)=><option key={clip.instance_id} value={clip.instance_id}>{index+1}. {clip.text.slice(0,32)}</option>)}</select></label>
        {selectedClip&&<><label>帧时间（源视频秒数）<input type="number" min={selectedClip.start_ms/1000} max={(selectedClip.end_ms-1)/1000} step={.001} value={frameMs/1000} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))change({frame_ms:Math.round(e.target.valueAsNumber*1000)});}}/></label><input aria-label="选择视频帧时间" type="range" min={selectedClip.start_ms} max={selectedClip.end_ms-1} step={1} value={frameMs} onChange={e=>change({frame_ms:Number(e.target.value)})}/></>}
        <button onClick={()=>change({frame_ms:null})}>使用作品起始帧</button><label>视频帧适配<select value={design.frame_fit} onChange={e=>change({frame_fit:e.target.value as CoverDesign["frame_fit"]})}><option value="contain">完整显示</option><option value="crop">填满裁切</option></select></label><p className="helper-text">保留源画面文字，不叠加软件字幕。</p>
      </details>
      <details open><summary>标题</summary><label>封面标题<textarea maxLength={500} rows={3} value={design.title} onChange={e=>change({title:e.target.value})}/></label><div className="cover-fields"><label>字体<select value={design.font_id??""} onChange={e=>change({font_id:e.target.value||null})}><option value="">默认中文字体</option>{fonts.map(font=><option key={font.id} value={font.id}>{font.name}</option>)}</select></label><label>字号<input type="number" min={16} max={300} value={design.font_size} onChange={e=>{if(e.target.valueAsNumber>=16&&e.target.valueAsNumber<=300)change({font_size:e.target.valueAsNumber});}}/></label><label>文字颜色<input type="color" value={design.text_color} onChange={e=>change({text_color:e.target.value})}/></label><label>对齐<select value={design.align} onChange={e=>change({align:e.target.value as CoverDesign["align"]})}><option value="left">左对齐</option><option value="center">居中</option><option value="right">右对齐</option></select></label><label>描边宽度<input type="number" min={0} max={12} value={design.stroke_width} onChange={e=>{if(e.target.valueAsNumber>=0&&e.target.valueAsNumber<=12)change({stroke_width:e.target.valueAsNumber});}}/></label><label>描边颜色<input type="color" value={design.stroke_color} onChange={e=>change({stroke_color:e.target.value})}/></label></div><label className="checkbox-field"><input type="checkbox" checked={design.bold} onChange={e=>change({bold:e.target.checked})}/>加粗</label><p className="helper-text">标题独立于作品名称，支持手动和自动换行。</p></details>
      <details><summary>位置与大小</summary><label>调整元素<select value={target} onChange={e=>setTarget(e.target.value as typeof target)}><option value="frame">视频帧</option><option value="title_box">标题框</option></select></label><div className="cover-fields">{(["x","y","width","height"] as const).map(key=><label key={key}>{{x:"水平位置 %",y:"垂直位置 %",width:"宽度 %",height:"高度 %"}[key]}<input type="number" min={key==="x"||key==="y"?-100:5} max={key==="x"||key==="y"?100:200} step={.1} value={Number((box[key]*100).toFixed(1))} onChange={e=>{const value=e.target.valueAsNumber/100;if(Number.isFinite(value))change({[target]:{...box,[key]:clamp(value,key==="x"||key==="y"?-1:.05,key==="x"||key==="y"?1:2)}});}}/></label>)}</div><div className="action-row"><button type="button" onClick={()=>change({[target]:{...box,x:(1-box.width)/2}})}>水平居中</button><button onClick={()=>change({[target]:{...box,y:(1-box.height)/2}})}>垂直居中</button><button onClick={()=>change(layout(design.aspect_ratio))}>恢复默认排版</button></div></details>
    </>}
    </fieldset>
    <div className="cover-actions"><button className="primary-button" disabled={busy||!dirty} onClick={()=>void save()}>{busy?"正在保存…":"保存封面设计"}</button><button disabled={busy||!dirty} onClick={()=>{setDesign(saved.design);setError("");}}>放弃封面修改</button></div><p role="status" className="helper-text">{busy?"正在保存或上传…":dirty?"封面有未保存修改，请保存或放弃后导出。":`封面已保存${saved.version?` · v${saved.version}`:" · 默认使用成片第一帧"}`}</p>
    {error&&<p role="alert">{error}</p>}
    {design.mode==="design"&&<><label>封面文件格式<select value={format} onChange={e=>setFormat(e.target.value as typeof format)}><option value="png">PNG</option><option value="jpg">JPG</option></select></label>{!dirty&&!busy&&saved.version>0?<a className="cover-download" href={`${route}/download?revision=${revision}&version=${saved.version}&format=${format}`} download>下载封面</a>:<p className="helper-text">保存设计后即可单独下载封面。</p>}</>}
    {design.mode==="first_frame"&&<p className="helper-text">封面从最终成片提取，视频导出完成后可在结果页下载。</p>}
  </section>;
}
