import { useEffect,useRef,useState } from "react";
import { recoverOutputPreview,startOutputPreview,readOutputExport,type OutputExportTask } from "./api";
export function RenderedPreview({project,collection,output,revision,title,sourceUrl,jumpTo}:{project:string;collection:string;output:string;revision:number;title:string;sourceUrl:string;jumpTo?:{ms:number;sequence:number}}) {
  const [task,setTask]=useState<OutputExportTask|null>(null);const [error,setError]=useState("");const [query,setQuery]=useState(0);const [source,setSource]=useState(false);
  const identity=useRef<string>(crypto.randomUUID());const force=useRef(false);const video=useRef<HTMLVideoElement>(null);
  useEffect(()=>{const controller=new AbortController();setError("");const retry=force.current;
    async function load(){try{let value=retry?null:await recoverOutputPreview(project,collection,output,revision,controller.signal);if(controller.signal.aborted)return;if(!value)value=await startOutputPreview(project,collection,output,revision,identity.current);if(!controller.signal.aborted)setTask(value);}catch(reason){if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"预览生成失败");}}
    void load();return()=>controller.abort();},[project,collection,output,revision,query]);
  const active=task?.status==="pending"||task?.status==="running";
  useEffect(()=>{if(!active||!task||error)return;const controller=new AbortController();const timer=setTimeout(()=>{readOutputExport(project,task.task_id,controller.signal).then(value=>{if(!controller.signal.aborted)setTask(value);}).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"预览状态读取失败");});},1000);return()=>{clearTimeout(timer);controller.abort();};},[active,task,error,project]);
  useEffect(()=>{if(jumpTo)setSource(true);},[jumpTo]);
  useEffect(()=>{if(source&&jumpTo&&video.current)video.current.currentTime=jumpTo.ms/1000;},[source,jumpTo]);
  const ready=task?.status==="succeeded"&&task.result?.revision===revision;
  return <div className="rendered-preview">{source?<><p className="muted">源素材定位（不是成片）</p><video key="source" ref={video} className="player" controls preload="metadata" src={sourceUrl} aria-label={`源素材 · ${title}`} onLoadedMetadata={()=>{if(video.current&&jumpTo)video.current.currentTime=jumpTo.ms/1000;}} onError={()=>setError("源素材无法播放")} /><button onClick={()=>{setSource(false);setError("");}}>返回成片预览</button></>:ready?<><video key={task.result!.media_url} ref={video} className="player" controls preload="metadata" src={task.result!.media_url} aria-label={`成片预览 · ${title}`} onError={()=>setError("成片预览无法播放")} /><p className="muted">低分辨率成片 · v{revision} · {(task.result!.duration_ms/1000).toFixed(1)} 秒</p></>:<div className="empty-preview"><p role="status">{task?.status==="failed"||task?.status==="cancelled"?`v${revision} 预览未完成`:`正在生成 v${revision} 成片预览…`}</p></div>}{(error||task?.error)&&<p role="alert">{error||task?.error}</p>}{(error||task?.status==="failed"||task?.status==="cancelled")&&<button onClick={()=>{force.current=task?.status==="failed"||task?.status==="cancelled";if(force.current)identity.current=crypto.randomUUID();setTask(null);setError("");setQuery(value=>value+1);}}>重试预览</button>}</div>;
}
