import { useEffect,useRef,useState } from "react";
import { recoverOutputPreview,startOutputPreview,readOutputExport,type OutputExportTask } from "./api";
import type {ExportOptions} from "./exportSettingsApi";
export function RenderedPreview({project,collection,output,revision,title,sourceUrl,jumpTo,options}:{project:string;collection:string;output:string;revision:number;title:string;sourceUrl:string;jumpTo?:{ms:number;sequence:number};options?:ExportOptions}) {
  const [task,setTask]=useState<OutputExportTask|null>(null);const [error,setError]=useState("");const [query,setQuery]=useState(0);const [source,setSource]=useState(false);
  const identity=useRef<string>(crypto.randomUUID());const force=useRef(false);const video=useRef<HTMLVideoElement>(null);
  const optionsKey=JSON.stringify(options??null);const [taskOptions,setTaskOptions]=useState("");
  const context=`${project}:${collection}:${output}:${revision}:${optionsKey}`;const lastContext=useRef(context);
  useEffect(()=>{const controller=new AbortController();setError("");const retry=force.current;
    async function load(){try{let value=retry?null:await recoverOutputPreview(project,collection,output,revision,controller.signal,options);if(controller.signal.aborted)return;if(!value)value=await startOutputPreview(project,collection,output,revision,identity.current,options);if(!controller.signal.aborted){setTask(value);setTaskOptions(optionsKey);}}catch(reason){if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"预览生成失败");}}
    if(lastContext.current!==context){identity.current=crypto.randomUUID();lastContext.current=context;}setTask(null);void load();return()=>controller.abort();},[project,collection,output,revision,query,optionsKey]);
  const active=task?.status==="pending"||task?.status==="running";
  useEffect(()=>{if(!active||!task||error)return;const controller=new AbortController();const timer=setTimeout(()=>{readOutputExport(project,task.task_id,controller.signal).then(value=>{if(!controller.signal.aborted)setTask(value);}).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"预览状态读取失败");});},1000);return()=>{clearTimeout(timer);controller.abort();};},[active,task,error,project]);
  useEffect(()=>{if(jumpTo)setSource(true);},[jumpTo]);
  useEffect(()=>{if(source&&jumpTo&&video.current)video.current.currentTime=jumpTo.ms/1000;},[source,jumpTo]);
  const ready=task?.status==="succeeded"&&task.result?.revision===revision&&taskOptions===optionsKey;
  return <div className="rendered-preview">{source?<><p className="muted">源素材定位（不是成片）</p><video key="source" ref={video} className="player" controls preload="metadata" src={sourceUrl} aria-label={`源素材 · ${title}`} onLoadedMetadata={()=>{if(video.current&&jumpTo)video.current.currentTime=jumpTo.ms/1000;}} onError={()=>setError("源素材无法播放")} /><button onClick={()=>{setSource(false);setError("");}}>返回成片预览</button></>:ready?<><video key={task.result!.media_url} ref={video} className="player" controls preload="metadata" src={task.result!.media_url} aria-label={`成片预览 · ${title}`} onError={()=>setError("成片预览无法播放")} >{task.result!.subtitle_track_url&&<track kind="subtitles" src={task.result!.subtitle_track_url} srcLang="und" label="作品字幕" default/>}</video><p className="muted">目标尺寸成片 · v{revision}{task.result!.width&&` · ${task.result!.width} × ${task.result!.height}`} · {(task.result!.duration_ms/1000).toFixed(1)} 秒{options?.subtitle_mode==="soft"?" · 软字幕由播放器显示":""}</p></>:<div className="empty-preview"><p role="status">{task?.status==="failed"||task?.status==="cancelled"?`v${revision} 预览未完成`:`正在生成 v${revision} 成片预览…`}</p></div>}{(error||task?.error)&&<p role="alert">{error||task?.error}</p>}{(error||task?.status==="failed"||task?.status==="cancelled")&&<button onClick={()=>{force.current=task?.status==="failed"||task?.status==="cancelled";if(force.current)identity.current=crypto.randomUUID();setTask(null);setError("");setQuery(value=>value+1);}}>重试预览</button>}</div>;
}
